name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
      - run: vp install
      - run: vp pack
      - run: vp check
      - run: vp test run
      - run: vp pm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
