name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - uses: voidzero-dev/setup-vp@13e7afb99c66525824db54e107d667216e795d37 # v1.14.0
        with:
          cache: true
      - run: vp install
      - run: vp pack
      - run: vp check
      - run: vp test run
      - run: vp pm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
