name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run format
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
